#!/usr/bin/env python

# A simple script that connects to a server and displays block headers

import time
import electrum_NMC

# start network
c = electrum_NMC.SimpleConfig()
s = electrum_NMC.daemon.get_daemon(c,True)
network = electrum_NMC.NetworkProxy(s,c)
network.start()

# wait until connected
while network.is_connecting():
    time.sleep(0.1)

if not network.is_connected():
    print_msg("daemon is not connected")
    sys.exit(1)

# 2. send the subscription
callback = lambda response: electrum_NMC.print_json(response.get('result'))
network.send([('blockchain.headers.subscribe',[])], callback)

# 3. wait for results
while network.is_connected():
    time.sleep(1)

